pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('checkout'){
            steps {
                script {
                    deleteDir()
                    git credentialsId: 'devopint', url: 'https://github.com/DevOpsINT/Course.git'
                }
            }
        }
        stage('shell command example') {
             input {
                    
                    message 'Enter Command'
                    id 'command'
                    ok 'OK'
                    parameters {
                        string defaultValue: 'COMMAND', description: '', name: 'command', trim: false
            steps {
                withCredentials([usernamePassword(credentialsId: 'devopint', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh 'git clone https://github.com/DevOpsINT/Course.git'    
                    sh 'git branch'
                    sh 'git checkout mops'
                    sh '$command'
                    sh 'git add .'
                    sh 'git commit -m "some"'
                    sh 'git push https://${USER}:${PASS}@github.com/DevOpsINT/Course'
                
                 
}
                
                

            }
        }
    }
}
