---

- name: Download Metricbeat
  raw: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ es_version }}-amd64.deb

- name: DPKG Metricbeat
  raw: dpkg -i metricbeat-{{ es_version }}-amd64.deb

- name: Move metricbeat.yml templates
  template:
    src: metricbeat.yml
    dest: /etc/metricbeat/metricbeat.yml
    #owner: 1002
    #group: kibana

#- name: Change the ELK output IP
  #raw: sed -i 's/localhost:9200/{{ elk_host }}:9200/g' /etc/metricbeat/metricbeat.yml

- name: Start Metricbeat
  raw: service metricbeat start

