---

- name: Create Working Folder For Dockerfile
  file:
    name: tmp
    state: directory
    mode: 755

- name: Remove Old Image Version
  docker_image:
    name: built-by-ansible
    tag: ex1
    force: yes
    state: absent

- name: Copy files from files & App_UT folders
  copy:
    src: "files/{{ item }}"
    dest: tmp
    force: yes
    owner: root
    group: root
    mode: '0755'
  with_items:
    - Dockerfile
    - Experiment.py
    - ExperimentTests.py

- name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    dest: tmp
  shell: docker build -t built-by-ansible:ex1 .

#- name: Build Docker image from Dockerfile
#  docker_image:
#    name: built-by-ansible
#    tag: ex1
#    path: tmp
#    state: present

- name: Running the container
  docker_container:
    name: built-by-ansible
    image: built-by-ansible:ex1
    state: started

- name: Check if container is running
  shell: docker ps


