---

- name: Create Working Folder For Dockerfile
  file:
    name: tmp
    state: directory
    mode: 755

- name: Remove Old Image Version
  docker_image:
    name: built-by-ansible
    tag: ex1
    force: yes
    state: absent

- name: Copy files from files & App_UT folders
  copy:
    src: "files/{{ item }}"
    dest: tmp
    force: yes
    owner: root
    group: root
    mode: '0755'
  with_items:
    - Dockerfile
    - Experiment.py
    - ExperimentTests.py

- name: Execute the command in remote shell; stdout goes to the specified file on the remote.
  shell: docker build -t "built-by-ansible:{{ buildVersion }}" ./tmp

- name: Running the container
  docker_container:
    name: "{{ buildVersion }}"
    image: "built-by-ansible:{{ buildVersion }}"
    state: started

- name: Save Docker Log Into Register
  shell: docker logs {{ buildVersion }}
  register: docker_log

- debug:
    var: docker_log.stdout

- set_fact:
        stop_enabled: true
  when: "'Hello world!' == docker_log.stdout"

- fail:
    msg: "The Conteiner Log Not Equal To Check String."
  when: "'Hello world!' != docker_log.stdout"



