- name: Rozana
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes

  pre_tasks: 
  - raw: sudo apt -qy update&& sudo apt install -qy python3&& sudo apt install -qy python&& sudo apt install -qy python-pip&& sudo pip install docker-py
  - setup:

  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Stop Docker Service
    service:
      name: docker
      state: stopped

  - name: Start Docker Service
    service:
      name: docker
      state: started
