---

-  gather_facts: no
   hosts : all
   remote_user: ubuntu
   become: yes

   tasks:
   - name: Install Docker
     apt:
       name: docker.io
       state: present

   - name: Stop Docker Service
     service:
       name: docker
       state: stopped

   - name: Start Docker Service
     service:
       name: docker
       state: started

   - name: Running the container
     docker_container:
       name: "{{ docker_hub_image }}"
       image: "{{ docker_hub_image }}"
       state: started

   - name: Save Docker Log Into Register
     shell: docker logs {{ docker_hub_image }}
     register: docker_log

   - debug:
       var: docker_log.stdout

   - set_fact:
          stop_enabled: true
     when: "'Hello world!' == docker_log.stdout"

   - fail:
          msg: "The Conteiner Log Not Equal To Check String."
     when: "'Hello world!' != docker_log.stdout"



