---
  
  - name: Install docker
    apt:
      name: docker.io
      state: present
        
  - name: Start docker service
    service:
      name: docker
      state: started

  - name: Create Folder Kibana
    file:
      path: /opt/kibana
      state: directory
      owner: 1000
      group: 1000
      mode: u+rw
      
  - name: Create Folder DB
    file:
      path: /opt/elasticsearch/data
      state: directory
      
  - name: Create Folder conf
    file:
      path: /opt/elasticsearch/config
      owner: 1000
      group: 1000
      mode: u+rw
      state: directory
      
  - name: Change Owner
    file:
      path: /opt/elasticsearch/config
      recurse: yes
      owner: 1000
      group: 1000
     
  - name: Change Owner
    file:
      path: /opt/elasticsearch/data
      recurse: yes
      owner: 1000
      group: 1000

 
 
