def targetIP = 'string'
def ipList
pipeline {
    options {
        timeout(time: 5, unit: 'MINUTES')
    }
    agent {
        label 'master'
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    git credentialsId: 'devopint', url: 'https://github.com/DevOpsINT/Course.git'
                    ipsList = sh script: 'cat jenkins_project/ips', returnStdout: true
                }
            }
        }
        stage('Provide IP address') {
            steps {
                    dir('jenkins_project/ansible') {  
                    script {
                        targetIP = input(id: 'userInput', message: 'choose ip address', parameters: ipsList)
                        println(targetIP)
                        //sh "sed -i 's/IP_ADDRESS/${targetIP}/g' hosts"
                        //sh "echo ansible-playbook -i hosts playbook.yml"
                    }
                    }
            }
        }
   }
}
