pipeline {
    options {
        timeout(time: 5, unit: 'MINUTES')
    }
    agent {
        label 'master'
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    git credentialsId: 'devopint', url: 'https://github.com/DevOpsINT/Course.git'
                    _ipsList = sh script: 'cat jenkins_project/ips', returnStdout: true
                    println(_ipsList)
                }
            }
        }
        stage('Provide IP address') {
            steps {
                    dir('jenkins_project/ansible') {  
                    script {
                        // choices parameter
                        targetIP = input message: 'Please choose ip address from the list below',
                        ok: 'confirm',
                        parameters: [choice(name: '', choices: "${_ipsList}", description: '')]
                        println(targetIP)
                        //string
                        targetIPstring = input(
                            id: 'userInput', message: 'ip add',
                            parameters: [
                                string(defaultValue: '0.0.0.0',
                                       description: 'ip address',
                                       name: 'IP')])
                        println(targetIPstring)
                        //sh "sed -i 's/IP_ADDRESS/${targetIP}/g' hosts"
                        //sh "echo ansible-playbook -i hosts playbook.yml"
                    }
                }
            }
        }
   }
}
