---
#
# Installing Kibana
#

# Install Kibana 

#- name: Install Kibana with apt
# apt:
# name: kibana
# update_cache: yes

- name: Run Kibana Docker
  docker_container:
    name: kibana
    hostname: kibana
    image: kibana:6.5.4
    state: started
    volumes:
       /opt/kibana/:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
    restart: yes
 
# Configurations

- name: Updating the config file to allow outside access
  lineinfile:
   destfile:/opt/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: 0.0.0.0'

- name: Defining server port
  lineinfile:
   destfile: /opt/kibana/kibana.yml
   regexp: 'server.port:'
   line: 'server.port: 5601'
    
- name: Defining Elasticsearch URL
  lineinfile:
   destfile:/opt/kibana/kibana.yml
   regexp: 'elasticsearch.url:'
   line: 'elasticsearch.url: "http://localhost:9200"'
   
# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started
- name: Move Kibana.yml
  template:
    src: templates/kibana.yml
    dest: /opt/kibana/kibana.yml
    owner: 1000
    group: 1000

   
     
