---
  hosts: {{ hosts }}
  gather_facts: no
  pre_tasks:
    - raw: sudo apt -qqy update&& sudo apt install -qy python3
  - setup:



  tasks:
   - name: Install common roles
     role:
      - "{{ docker, become: yes }}"


   - name: Install role
     role:
      - "{{ {{ role }}, become: yes }}"
