---
- name: Gadi First Playbook (Install Python, Install Docker & Run, Install Jenkins & run)
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes

  pre_tasks: 
  - raw: sudo apt -qqy update&& sudo apt install -qy python3 && sudo pip install docker-py 
  - setup:

  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Stop Docker Service
    service:
      name: docker
      state: stopped

  - name: Start Docker Service
    service:
      name: docker
      state: started

  - name: Create Working Folder For Jenkisn
    file: 
      path: /opt/jenkins
      state: directory

  - name: Change Directory Owner & Group
    file:
      path: /opt/jenkins
      owner: 1000
      group: 1000

  - name: Start Jenkins Container
    docker_container:
      name: jenkins
      image: jenkins/jenkins:lts
      state: started
      ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - /opt/jenkins:/var/jenkins_home
