---
- name: This is a playbook
  hosts: all
  gather_facts: false

- name: Gadi First Playbook (Install Python, Install Docker & Run, Install Jenkins & run)
  hosts: all
  gather_facts: no

  pre_tasks: 
  - raw: sudo apt -qqy update&& sudo apt install -qy python3  
  - setup:

  tasks:

  - name: install "{{ service }}"
    apt:
      name: "{{ service }}"
      state: present

  - name: "stop {{ service }} service"
    service:
      name: "{{ service }}"
      state: stopped

  - name: copy config file
    template:
      src: default.conf
      dest: "/etc/{{ service }}"

  - name: start "{{ service }}" service
    service: 
      name: "{{ service }}"
      state: started


  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Stop Docker Service
    service:
      name: docker
      state: stopped

  - name: Start Docker Service
    service:
      name: docker
      state: started

  - name: Create Working Folder For Jenkisn
    file: 
      path: /opt/jenkins
      state: directory

  - name: Change Directory Owner & Group
    file:
      path: /opt/jenkins
      owner: 1000
      group: 1000

  - name: Start Jenkins Container
    docker_container:
      name: Jen
      image: jenkins/jenkins:lts
      state: started
      ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - /opt/jenkins:/var/jenkins_home

