---
- name: Elasticsearch module
  hosts: all
  vars:
      package_url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.2.0-amd64.deb
      es_private_ip: 192.168.1.4
  remote_user: "{{ user }}"
  become: yes
  pre_tasks:
     - raw: apt update && apt install -y python-pip  && pip install docker-py 
  tasks:
     - name: Install and configure metricbeat in remote host
       shell: |
         curl -L -O "{{ package_url }}"
         dpkg -i  "/home/{{ user }}/{{ package_url.split('/')[6] }}"
         sed  -i "s/\(hosts:\)\s\{1,\}\(.*\)/\1 [ """\""{{ es_private_ip }}:9200"""\"" ] /" /etc/metricbeat/metricbeat.yml
         metricbeat setup --dashboards -e -E output.elasticsearch.hosts=['{{ es_private_ip }}:9200'] -E setup.kibana.host="{{ es_private_ip}}:5601"
     - name: Enable metricbeat service if is disabled
       systemd:
         state: started
         name: metricbeat    
          

